### ISSUE TITLE
why is appernetic.io not working? 

### ISSUE THREAD

**Issue by appernetic2** [appernetic/issues#1]

**Comment by appernetic2** [comment]
The log in still has some problems I need reload appernetic.io to enter appernetic2

**Comment by appernetic** [comment]
You mean the logo upp to the left?

**Comment by appernetic** [comment]
1. First do a Sync in your dashboard.
2. To change navigation links go here: https://github.com/appernetic2/appernetic-hugo-project/blob/master/themes/hugo-bootstrap/data/Menu.toml
3. Edit an commit.
4. Sync again in your appernetic.io dashboard.

**Comment by appernetic** [comment]
Closing this one now!
